config/routes.rb
Rails.application.routes.draw do

  root "artists#index"

  get 'artists/alphabetical' => 'artists#alphabetical', as: :artists_alphabetical
  get 'artists/creationdate' => 'artists#creationdate', as: :artists_creationdate

  resources :artists do
    resources :songs
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs

  mount_uploader :image, ImageUploader

  def self.order_by_name
    sort_by { |artist| artist[:name] }
  end

  def self.order_by_creation_date
    sort_by { |artist| artist[:name] }
  end

end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  def alphabetical
    @artists = Artist.order(:name)
    render 'index'
  end

  def creationdate
    @artists = Artist.order(:created_at)
    render 'index'
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @song = Song.new
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
      @songs = @artist.songs
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require( :artist ).permit( :name, :image)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.where(artist_id: params[:artist_id])
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
    @artist = Artist.find(params[:artist_id])
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to root_path, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @deleted_song = @song.destroy
    respond_to do |format|
      format.html { redirect_to artist_songs_url(params[:artist_id]), notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
      format.js {}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require( :song ).permit( :title, :artist_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_artist.html.erb
<div class="fp_artist_box">
  <div class="fp_artist"><%= link_to artist.name, artist_songs_path(artist.id) %></div>
  <% if artist.image.thumbnail.url %>
    <div class="fp_thumbnail"><%= image_tag(artist.image.thumbnail.url, size: "66x66") %></div>
  <% end %>
</div>

app/views/artists/_form.html.erb
<%= form_for(artist) do |f| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artists</h1>

<%= link_to "Sort alphabetical", artists_alphabetical_path %>
<%= link_to "Sort by creation date", artists_creationdate_path %>

<div id='artists_overview'>
  <%= render @artists %>
</div>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @artist.name %></h1>

<div>
  <% if @artist.image.thumbnail.url %>
    <%= image_tag(@artist.image.thumbnail.url) %>
  <% end %>
</div>
<div class="songs_overview">
  <%= render @songs %>
</div>
<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Songdb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for [@artist, @song], remote: true do |f| %>
<%= f.text_field  :title %>
<%= f.hidden_field :artist_id, value: @artist.id %>
<%= f.button :submit %>
<% end %>

app/views/songs/_song.html.erb
<div class="song" id="song-<%= song.id %>">
  <%= song.title %>
  <div class="del_button"><%= link_to "Delete", artist_song_path(params[:artist_id],song.id), remote: true, method: :delete, data: { confirm: "Are you 100% sure you want to remove this iconic song?" } %>
  </div>
</div>

app/views/songs/create.js.erb
$("<%= escape_javascript(render @song) %>").appendTo("#songlist");
$('#song-form').slideUp(350);

app/views/songs/destroy.js.erb
$("#song-<%= @deleted_song.id %>").remove();

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Songs</h1>

<div id="song-form" style="display:none;"></div>
<%= link_to 'New Song', new_artist_song_path(params[:artist_id]), remote: true, :id => "newsong" %>

<div id="songlist">
  <%= render @songs %>
</div>
<div>
  <br />
<%= link_to '[Back to artists]', artists_path %>
</div>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

app/views/songs/new.js.erb
$('#song-form').html("<%= j (render 'form') %>");
$('#song-form').slideDown(350);

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>